quay:
  namespace: quay-enterprise
  component:
  - name: clair
    managed: true
  - name: horizontalpodautoscaler
    managed: true
  - name: mirror
    managed: true
  - name: monitoring
    managed: true
  - name: postgres
    managed: false
  - name: redis
    managed: false
  - name: objectstorage
    managed: false
  - name: route
    managed: true
  - name: tls
    managed: true
  - name: quay
    managed: true
  - name: clairpostgres
    managed: false
  configBundleSecret:
    deploy: true
    name: quay-init-config-bundle-secret
  setup:
    admin:
      # Generated password is saved to the 'quay-init-token' secret in the configured namespace
      name: quayadmin
      email: quayadmin@nvd.lab
    #user:
      # Generated password is saved to the 'quay-user' secret in the configured namespace
      # The API only allows the creation of superusers
    #  name: developer1
    #  email: developer1@myorg.com

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

global:
  hub:
    clustername: NAME
    domain: DOMAIN

  quay:
    org:
      name: devel
      email: devel@myorg.com
    repo: example

clusterGroup:
  name: AUTOMATIC
